# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3a288008931617ce15d3d04ae4230340f20a99d325168dfc118fac877e1632d6c54bd227c52d2b927c39f8a283aee2426ac1e0226e0c4610c400e1f6dbdda8f9

test:
  secret_key_base: 0d6a1a34db47c478ce07afe9716f605b4f1f2e994923b536cd3aa1b2fa1af9d27fb8a7917c77ca590041870a9d63dad673c2d2789637623d284bd2310a610a6f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
